version: "3.5"
services:
  wildfly:
    #image: quay.io/wildfly/wildfly:27.0.0.Final-jdk11
    build: .
    ports:
      - "8080:8080"
      - "9990:9990"
    links:
      - etcd
    depends_on:
      - etcd
  etcd:
    image: docker.io/bitnami/etcd:3.5
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379
      - 2380:2380